"""add Department

Revision ID: 18875537bc59
Revises: d6c505538d4c
Create Date: 2024-07-01 12:21:22.962062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18875537bc59'
down_revision = 'd6c505538d4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
